name: Verify

# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
permissions:
  actions: none
  checks: none
  contents: none
  deployments: none
  id-token: none
  issues: none
  discussions: none
  packages: none
  pages: none
  pull-requests: none
  repository-projects: none
  security-events: none
  statuses: none

on: [push, pull_request]

jobs:
  mingw:
    runs-on: ubuntu-latest
    timeout-minutes: 40
    name: Meterpreter MinGW Docker Build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Compile
        run: |
          cd c/meterpreter
          script --return --command 'make docker'

  python:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-11
          - windows-2019
          - ubuntu-20.04
        runtime_version:
          - 2.7
          - 3.6
          - 3.8
          - 3.11

    timeout-minutes: 40
    runs-on: ${{ matrix.os }}
    name: Python ${{ matrix.runtime_version }} ${{ matrix.os }}

    env:
      # Ignore messages generated by Pip: 'DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020'
      PIP_DISABLE_PIP_VERSION_CHECK: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.runtime_version }}

      - name: Install mock
        if: ${{ matrix.runtime_version <= 3.3 }}
        run: |
          pip install mock

      - name: run tests
        run: |
          cd python/meterpreter
          python -m unittest discover -v ./tests
